Repository hellonayeon/recipe-recommend-service, pull requests merged in 2021-09, with the labels that each got.

#10 Feautre/09 overlap feature delete
  app.py
  templates/index.html
Labels: bug, enhancement

#17 레시피 카드 크기 통일, 순서 정렬 기능 추가 및 수정 #12, #14
  templates/index.html
Labels: bug, enhancement

#24 상세 페이지 레시피 프론트 부분 수정완료
  FIRST_PAGE/app.py
  FIRST_PAGE/data_init.py
  FIRST_PAGE/templates/index.html
  app.py
  templates/index.html
Labels: bug, enhancement

#29 레시피 카드(사진,설명글) 정렬 틀어짐 문제 수정 #28
  static/helpmymenu.css
  static/helpmymenu.js
Labels: bug

#35 재료에서 양념에 포함되는 항목 제거 #34
  app.py
Labels: bug

#40 Feature/33 autocomplete
  app.py
  static/helpmymenu.js
  templates/index.html
Labels: enhancement
